name: Release and publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 21.x]
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run test
        run: pnpm run test

  release-please-action:
    runs-on: ubuntu-latest
    needs: ['test']
    steps:
      - uses: google-github-actions/release-please-action@main
        id: release-action
        with:
          release-type: node
    outputs:
      is-release-created: ${{ steps.release-action.outputs.release_created }}

  release:
    runs-on: ubuntu-latest
    needs: ['release-please-action']
    if: ${{ needs.release-please-action.outputs.is-release-created }}
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@main
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
